Feat/Ban-user
CindyGraffin/wheel_us_go pull request #65
Opened 2022-09-14 13:05 UTC by EresseaNui

2022-09-17 22:06 UTC, CindyGraffin approved these changes

2022-09-17 22:06 UTC, CindyGraffin commented on src/components/dashboard/dashboardUser/DashboardUserTable.spec.tsx
>      test("la modal doit s'ouvrir quand je clique su l'oeil", () => {
manque une lettre "su**r** l'oeil"
Comme j'ai jamais rien à dire faut bien que je t'embête un peu lol

2022-09-17 22:06 UTC, CindyGraffin commented on src/services/userService.ts
> +        await api.post(`/users/ban/${id}`).catch((err) => console.error(err));
supprimer le controle.error par une fonction de gestion de l'erreur

2022-09-19 14:08 UTC, StudioAzur requested changes

2022-09-19 14:08 UTC, StudioAzur commented on src/components/UI/Modal/dashboard/DashBoardUserInformation/DashboardUserInformationModal.spec.tsx
> +    const onclickPromise = async () => {
Enlever le console.log 🗡️

2022-09-19 14:08 UTC, StudioAzur commented on src/components/dashboard/dashboardUser/DashboardUserTable.spec.tsx
> +    const onclickPromise = async () => {
Enlever le console.log 👯‍♂️

2022-09-19 14:22 UTC, EresseaNui commented on src/components/dashboard/dashboardUser/DashboardUserTable.spec.tsx
> +    const onclickPromise = async () => {
🖕

2022-09-19 14:22 UTC, EresseaNui commented on src/components/UI/Modal/dashboard/DashBoardUserInformation/DashboardUserInformationModal.spec.tsx
> +    const onclickPromise = async () => {
🖕

2022-09-19 14:25 UTC, StudioAzur approved these changes

2022-09-19 14:25 UTC, merged